// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_api_keys from "./routes/admin/api-keys.tsx";
import * as $admin_changelog from "./routes/admin/changelog.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_organization from "./routes/admin/organization.tsx";
import * as $admin_posts from "./routes/admin/posts.tsx";
import * as $admin_posts_id_ from "./routes/admin/posts/[id].tsx";
import * as $admin_posts_new from "./routes/admin/posts/new.tsx";
import * as $admin_settings from "./routes/admin/settings.tsx";
import * as $admin_users from "./routes/admin/users.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $organizations from "./routes/organizations.tsx";
import * as $ApiKeyForm from "./islands/ApiKeyForm.tsx";
import * as $ApiKeysTable from "./islands/ApiKeysTable.tsx";
import * as $AuthCheck from "./islands/AuthCheck.tsx";
import * as $DashboardContent from "./islands/DashboardContent.tsx";
import * as $HeaderAuthControls from "./islands/HeaderAuthControls.tsx";
import * as $LocationForm from "./islands/LocationForm.tsx";
import * as $LocationList from "./islands/LocationList.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MobileNavDrawer from "./islands/MobileNavDrawer.tsx";
import * as $MobileNavigation from "./islands/MobileNavigation.tsx";
import * as $Modal from "./islands/Modal.tsx";
import * as $OrganizationInfo from "./islands/OrganizationInfo.tsx";
import * as $OrganizationList from "./islands/OrganizationList.tsx";
import * as $PostEditor from "./islands/PostEditor.tsx";
import * as $PostForm from "./islands/PostForm.tsx";
import * as $PostsTable from "./islands/PostsTable.tsx";
import * as $SettingsForm from "./islands/SettingsForm.tsx";
import * as $ThemeSwitcher from "./islands/ThemeSwitcher.tsx";
import * as $UserForm from "./islands/UserForm.tsx";
import * as $UsersTable from "./islands/UsersTable.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/api-keys.tsx": $admin_api_keys,
    "./routes/admin/changelog.tsx": $admin_changelog,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/organization.tsx": $admin_organization,
    "./routes/admin/posts.tsx": $admin_posts,
    "./routes/admin/posts/[id].tsx": $admin_posts_id_,
    "./routes/admin/posts/new.tsx": $admin_posts_new,
    "./routes/admin/settings.tsx": $admin_settings,
    "./routes/admin/users.tsx": $admin_users,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/organizations.tsx": $organizations,
  },
  islands: {
    "./islands/ApiKeyForm.tsx": $ApiKeyForm,
    "./islands/ApiKeysTable.tsx": $ApiKeysTable,
    "./islands/AuthCheck.tsx": $AuthCheck,
    "./islands/DashboardContent.tsx": $DashboardContent,
    "./islands/HeaderAuthControls.tsx": $HeaderAuthControls,
    "./islands/LocationForm.tsx": $LocationForm,
    "./islands/LocationList.tsx": $LocationList,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MobileNavDrawer.tsx": $MobileNavDrawer,
    "./islands/MobileNavigation.tsx": $MobileNavigation,
    "./islands/Modal.tsx": $Modal,
    "./islands/OrganizationInfo.tsx": $OrganizationInfo,
    "./islands/OrganizationList.tsx": $OrganizationList,
    "./islands/PostEditor.tsx": $PostEditor,
    "./islands/PostForm.tsx": $PostForm,
    "./islands/PostsTable.tsx": $PostsTable,
    "./islands/SettingsForm.tsx": $SettingsForm,
    "./islands/ThemeSwitcher.tsx": $ThemeSwitcher,
    "./islands/UserForm.tsx": $UserForm,
    "./islands/UsersTable.tsx": $UsersTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
